export default function ChamadoManual() {
  return <section className="grid md:grid-cols-2 gap-4 my-5 text-sm text-ws-secondary">
    <details className="rounded-xl border border-ws-border bg-ws-panel p-4"><summary className="cursor-pointer font-semibold text-ws-bright">Manual: como abrir e acompanhar um chamado</summary>
      <ol className="list-decimal pl-5 mt-3 space-y-2"><li>Confira sua empresa em Meu Perfil. Clique em Novo chamado.</li><li>Informe um título objetivo, categoria e prioridade conforme o impacto no trabalho.</li><li>Descreva o erro, quando começou e o que já tentou. Informe telefone e ID da ferramenta remota.</li><li>Selecione até 5 imagens PNG, JPEG ou GIF, somando até 25 MB; até 16 megapixels por imagem. Evite incluir senhas nas capturas.</li><li>Envie e guarde o ticket. Ele combina a empresa com uma sequência global de 11 dígitos, por exemplo MalibruMtz00000000001.</li><li>Selecione o chamado para acompanhar o prazo, baixar imagens e conversar com o suporte.</li></ol>
    </details>
    <details className="rounded-xl border border-ws-border bg-ws-panel p-4"><summary className="cursor-pointer font-semibold text-ws-bright">Manual: SLA e atendimento</summary>
      <div className="mt-3 space-y-2"><p>SLA é o prazo para o primeiro atendimento: alta (trabalho interrompido) 2 horas úteis; média (existe alternativa) 4; baixa (dúvidas e solicitações planejadas) 8.</p><p>O expediente considerado é de segunda a sexta, 8h às 18h, no horário de Brasília, sem exclusão automática de feriados. Fora do expediente, a contagem começa no próximo período útil.</p><p>O primeiro atendimento é registrado quando o suporte responde ou muda o status para Em atendimento, Aguardando usuário, Resolvido ou Fechado. O prazo de resolução depende da análise técnica.</p><p>O SLA de primeiro atendimento não reinicia ao reabrir nem é pausado por Aguardando usuário. Cancelados sem atendimento são excluídos dos indicadores de SLA. Chamados antigos sem prazo aparecem como legado.</p><p>Para o atendente: selecione o chamado, analise a descrição e as imagens, responda pela conversa e atualize o status. O último atendente que respondeu ou atuou no status fica registrado no relatório.</p></div>
    </details>
  </section>;
}
